# Generated by Django 4.0.4 on 2022-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employeemptt_paid_salary_inf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemptt',
            name='paid_salary_inf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
